name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Auth to Google Cloud Services
        run: |
          gcloud auth login --brief --cred-file=${{ secrets.API_KEY }}
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build Docker Image
        run:
          docker build -t europe-west4-docker.pkg.dev/togetherboxd-389917/gateway-repo/api-gateway:${{ github.sha }} .

      - name: Push Image to Registry
        run:
          docker push europe-west4-docker.pkg.dev/togetherboxd-389917/gateway-repo/api-gateway:${{ github.sha }}

      - name: Deploy to GKE Cluster
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials togetherboxd-cluster --zone europe-west4
          sleep 5s
          kubectl set image deployment/api-gateway api-gateway=europe-west4-docker.pkg.dev/togetherboxd-389917/gateway-repo/api-gateway:${{ github.sha }}
