name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Setup, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
      
      - name: Build (Optional)
        run: npm run build --if-present

      - name: Test
        run: npm test
  
  # Test the key
      - name: Debug API Key
        run: echo "${{ secrets.API_KEY }}"
      
  # Authentication to google cloud services
      - name: Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          credentials_json: '${{ secrets.API_KEY }}'
          token_format: 'access_token'
          create_credentials_file: true
          
  # Setting up tools for iteracting with google cloud services
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        
  #Check google cloud connection
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Auth to google cloud services
        run: |
          gcloud auth login --brief --cred-file=${{ steps.auth.outputs.credentials_file_path }}
          gcloud auth configure-docker europe-west4-docker.pkg.dev
      - name: Build Docker Image
        run:
          docker build -t europe-west4-docker.pkg.dev/tboxd-399816/gateway-repo/gateway-app:${{ github.sha }} .

  # Snyk vulnerability scan
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: Scan for vulnerabilities with Snyk
        run: snyk test --severity-threshold=medium || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
        id: snyk-test


      - name: k6 Load Test
        uses: k6io/action@v0.1
        with:
          filename: k6test.js
          cloud: true
          token: ${{secrets.K6_CLOUD_API_TOKEN}}


      - name: Push Image to Registry
        run:
          docker push europe-west4-docker.pkg.dev/tboxd-399816/gateway-repo/gateway-app:${{ github.sha }}

      - name: Deploy to GKE Cluster
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials tboxd-cluster --zone europe-west4
          sleep 5s
          kubectl set image deployment/gateway-app gateway-app=europe-west4-docker.pkg.dev/tboxd-399816/gateway-repo/gateway-app:${{ github.sha }}

          