name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Setup, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.API_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        
      - name: Build Docker Image
        run:
          docker build -t europe-west4-docker.pkg.dev/togetherboxd-389917/gateway-repo/gateway-api:${{ github.sha }} .
      
      - name: Authenticate Docker to Google Artifact Registry
        run: gcloud auth configure-docker --quiet
      
      - name: Push Image to Registry
        run: |
          docker push europe-west4-docker.pkg.dev/togetherboxd-389917/gateway-repo/gateway-api:${{ github.sha }}
      

      - name: Deploy to GKE Cluster
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials togetherboxd-cluster --zone europe-west4
          sleep 5s
          kubectl set image deployment/gateway-api gateway-api=europe-west4-docker.pkg.dev/togetherboxd-389917/gateway-repo/gateway-api:${{ github.sha }}
